# Generated by Django 2.0.3 on 2018-09-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_block_st'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='st',
        ),
    ]
