# Generated by Django 2.0.3 on 2018-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20180923_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='depth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='width',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
