# Generated by Django 2.0.3 on 2018-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_auto_20180923_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
