# Generated by Django 2.0.3 on 2018-09-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoID', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
    ]
